name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"

include-labels:
  - "Major Version"
  - "Minor Version"
  - "Patch Version"

categories:
  - title: "Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Documentation"
    labels:
      - "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
version-resolver:
  major:
    labels:
      - "Major Version"
  minor:
    labels:
      - "Minor Version"
  patch:
    labels:
      - "Patch Version"
  default: patch
template: |
  ## Changes

  $CONTRIBUTORS

  $CHANGES
