name: Testing

on: push

jobs:
  test:
    strategy:
      matrix:
        node: ["14", "12"]
    name: unit test @ node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node }}"
      - name: Install dependencies
        run: yarn install
      - run: yarn test
  e2e:
    strategy:
      matrix:
        package: ["components-e2e", "research-e2e"]
    name: "${{ matrix.package }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - run: yarn nx run "${{ matrix.package }}":e2e
