
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v1
       with:
          node-version: '14'
     - name: Install dependencies
       run: yarn install
     - name: Lint
       run: yarn fmt
  test:
    strategy:
      matrix:
        node: [ '14', '12' ]
    name: unit test @ node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v1
       with:
          node-version: '${{ matrix.node }}'
     - name: Install dependencies
       run: yarn install
     - run: yarn test:all
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Setup node
       uses: actions/setup-node@v1
       with:
          node-version: '14'
     - name: Install dependencies
       run: yarn install
     - run: yarn e2e --headless

  