name: Testing

on: push

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Lint
        run: yarn fmt
  test:
    strategy:
      matrix:
        node: ["14", "12"]
    name: unit test @ node ${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node }}"
      - name: Install dependencies
        run: yarn install
      - run: yarn test
  e2e:
    strategy:
      matrix:
        package: ["core-e2e", "research-e2e"]
    name: "${{ matrix.package }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn install
      - name: Build css
        run: yarn build:css
      - name: Run Integration test
        run: yarn nx run "${{ matrix.package }}":e2e
  lighthouse:
    strategy:
      matrix:
        app: ["research", "core"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: install
        run: yarn install
      - name: build
        run: yarn build
      - name: Install lighthouse
        run: npm install -g @lhci/cli
      - name: run lighthouse
        run: lhci --config=./lighthouse/${{matrix.app}}.js autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
