name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    strategy:
      matrix:
        svc: [website, app]
    name: Deploy ${{matrix.svc}}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Get short SHA
        id: hash
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./apps/${{matrix.svc}}/Dockerfile
          tags: perfolio/web-${{matrix.svc}}:${{ steps.hash.outputs.sha8 }}

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}

      - name: Schedule ${{matrix.svc}}
        run: terraform apply -auto-approve -target=nomad_job.${{matrix.svc}}
        env:
          TF_VAR_nomad: "{address=\"${{secrets.NOMAD_ADDR}}\",token=\"${{secrets.NOMAD_TOKEN\"}"
          TF_VAR_tag: ${{ steps.hash.outputs.sha8 }}