name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    strategy:
      matrix:
        svc: [website, app]
    name: Deploy ${{matrix.svc}}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          
      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./apps/${{matrix.svc}}/Dockerfile
          tags: perfolio/web-${{matrix.svc}}:latest

      - name: Setup nomad
        run: |
            curl https://releases.hashicorp.com/nomad/1.0.1/nomad_1.0.1_linux_amd64.zip -p nomad.zip
            unzip nomad.zip

      - name: Schedule ${{matrix.svc}}
        run: ./nomad job run ./deployments/jobs/${{matrix.svc}}.hcl
        env:
          NOMAD_ADDR: ${{secrets.NOMAD_ADDR}}
          NOMAD_TOKEN: ${{secrets.NOMAD_TOKEN}}
