name: Deploy

on:
  push:
    branches: [ main ]
jobs:
  release:
    strategy:
      matrix:
        svc: [website, app]
    name: Release ${{matrix.svc}}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./apps/${{matrix.svc}}/Dockerfile
          tags: |
            perfolio/web-${{matrix.svc}}:$(echo ${GITHUB_SHA} | cut -c1-8)
            perfolio/web-${{matrix.svc}}:latest

      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
  deploy:
    needs: release
    name: Deploy to Nomad
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2

      - name: Initialize Terraform
        run: terraform -chdir=deployments init

      - name: Schedule ${{matrix.svc}}
        run: terraform -chdir=deployments apply -auto-approve -var "tag=$(echo ${GITHUB_SHA} | cut -c1-8)"
        env:
          TF_VAR_nomad: "{address=\"${{secrets.NOMAD_ADDR}}\",token=\"${{secrets.NOMAD_TOKEN}}\"}"