name: Deploy

on:
  push:
    branches: [ master, main ]
jobs:
  deploy:
    strategy:
      matrix:
        package: ["core", "research", "docs"]
    name: deploy-${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: build
        run: yarn nx export ${{matrix.package}} --with-deps
        env:
          NODE_ENV: production

      - name: deploy
        run: yarn nx deploy ${{matrix.package}}
        env:
          NETLIFY_TOKEN: ${{secrets.NETLIFY_TOKEN}}