name: Lighthouse

on: push

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: yarn install && yarn add -g @lhci/cli
      - run: yarn build
      - run: lhci autorun