name: Release

on:
  push:
    branches: [ master, main ]
jobs:
  release:
    strategy:
      matrix:
        package: ["core", "data", "docs"]
    
    name: release-${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Load dependencies from cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build app
        run: yarn nx export ${{matrix.package}} --with-deps --skip-nx-cache
        env:
          NODE_ENV: production


      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          context: ./dist/packages/${{matrix.package}}/exported
          push: true
          tags: perfolio/web-${{matrix.package}}