name: Release

on:
  pull_request:
    branches: [ release* ]



jobs:
  test:
    strategy:
      matrix:
        package: ["core", "research"]
    name: release-${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: build
        run: yarn nx run ${{matrix.package}}:build:production --with-deps --skip-nx-cache

      - name: unit-test
        run: yarn nx run ${{matrix.package}}:test --with-deps --skip-nx-cache

      - name: e2e-test
        run: yarn nx e2e ${{matrix.package}}-e2e --with-deps --skip-nx-cache --headless

      - name: lighthouse
        run: yarn lhci autorun
        env:
          LHCI_CONFIG: lighthouse/${{matrix.package}}.js
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

