name: Release

on:
  push:
    branches: [ main ]
jobs:
  release:
    strategy:
      matrix:
        svc: [website, app]
    name: Release ${{matrix.svc}}
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./apps/${{matrix.svc}}/Dockerfile
          tags: |
            perfolio/web-${{matrix.svc}}


      - name: Setup go
        uses: actions/setup-go@v2
      - name: Install levant
        run: |
          git clone git://github.com/hashicorp/levant.git
          cd levant
          make build
      - name: Import Secrets
        uses: hashicorp/vault-action@v2.1.1
        with:
          url: ${{secrets.VAULT_ADDR}}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
              secret/kv/prod/nomad address | NOMAD_ADDR ;
              secret/kv/prod/nomad root_token | NOMAD_TOKEN
      - name: Schedule erebus
        run: |
          ./levant/bin/levant deploy \
            -force=true \
            -force-count \
          ./deployments/${{matrix.svc}}.hcl
