name: Release

on:
  push:
    branches: [ master, main ]
jobs:
  release:
    strategy:
      matrix:
        package: ["core", "data", "docs"]
    
    name: release-${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          build-args: 
            SERVICE=${{matrix.package}}
          push: true
          tags: perfolio/web-${{matrix.package}}