name: Release

on:
  push:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        svc: [website, app]
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        use: actions/checkout@v2
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 14
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: ''
          target-branch: main
          skip-tag: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          


      - run: echo ${{github.ref}}
      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./build/Dockerfile
          build-args: 
            SERVICE=${{matrix.svc}}
          tags: |
            perfolio/web-${{matrix.svc}}:${{steps.get_version.outputs.VERSION}}
            perfolio/web-${{matrix.svc}}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
      
      - name: Init
        run: terraform -chdir=deployments init
      - name: Apply
        run: |
          echo "{\"package_version\": \"${{steps.get_version.outputs.VERSION}}\"}" > ./deployments/version.auto.tfvars.json
          terraform -chdir=deployments apply -auto-approve -var "package_version=${{TF_VAR_package_version}}"
