name: Release

on:
  push:
    branches: [ master, main ]
jobs:
  build:
    strategy:
      matrix:
        package: ["core", "data", "docs", "analytics"]
    
    name: release-${{matrix.package}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          build-args: 
            SERVICE=${{matrix.package}}
          push: true
          tags: perfolio/web-${{matrix.package}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh terraform apply
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.DEPLOY_KEY }}
        port: ${{ secrets.DEPLOY_PORT }}
        script: cd ~/deploy/prod && sh run.sh