name: Release

on:
  push:
    branches: [ main ]
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: "Check out source code"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 14

      - name: Release
        run: npx release -ops